json.avatar_file_name current_user.avatar.url
json.first_name current_user.first_name
json.last_name current_user.last_name
json.email current_user.email
json.notification_frequency current_user.notification_frequency